# Generated by Django 6.0.3 on 2026-03-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_almoco', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='email_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='nome_usuario',
        ),
    ]
