# Generated by Django 6.0.3 on 2026-03-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_almoco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
