# Generated by Django 6.0.3 on 2026-04-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_almoco', '0003_rename_email_usuario_email_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_almoco.usuario')),
            ],
        ),
    ]
