# Generated by Django 6.0.3 on 2026-04-18 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_almoco', '0004_alter_usuario_email_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_encomenda',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
